name: KBOT-CICD

on:
  push:
    branches:
      - main
      # - develop

env:
  TARGETARCH: amd64
  REGISTRY: ghcr.io
  
jobs:
  ci:
    name: CI
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create full registry path
        run: echo "REGISTRY_FULL=${{ env.REGISTRY }}/${{ github.actor }}" >> $GITHUB_ENV
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ env.REGISTRY_FULL }}
        run: make image push TARGETARCH=$TARGETARCH
      - name: Clean
        env:
          APP: "kbot"
          REGISTRY: ${{ env.REGISTRY_FULL }}
        run: make clean TARGETARCH=$TARGETARCH
      
  cd:
    name: CD
    needs: ci
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.version=strenv(VERSION)' helm/Chart.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push
